"""业务总时限与流式收尾预算；模型调用次数和取消机制仍独立生效。"""

PLANNING_TIMEOUT_SECONDS = 120
PLANNING_STREAM_TIMEOUT_SECONDS = PLANNING_TIMEOUT_SECONDS + 10
DEFAULT_STREAM_TIMEOUT_SECONDS = 70
WORKFLOW_TIMEOUT_SECONDS = 65
# 传给 SDK 的网络 I/O 等待时间；持续收包时仍由上面的业务总时限兜底。
WORKFLOW_MODEL_TIMEOUT_SECONDS = 25
